version: '3.8'

services:
  db:
    image: postgres:16
    container_name: control-stock-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: stock_control_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-stock-control-network

  api:
    build: .
    container_name: stock-control-api
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend-stock-control-network

volumes:
  db_data:

networks:
  backend-stock-control-network: